In [ ]:
dataset = [ ['Lait', 'Oignon', 'Noix de muscade', 'Haricots rouges', 'Œufs', 'Yaourt'],
          ['Aneth', 'Oignon', 'Noix de muscade', 'Haricots rouges', 'Œufs', 'Yaourt'],
           ['Lait', 'Pomme', 'Haricots rouges', 'Œufs'],
           ['Lait', 'Licorne', 'Maïs', 'Haricots rouges', 'Yaourt'], 
           ['Maïs', 'Oignon', 'Oignon', 'Haricots rouges', 'Crème glacée', 'Œufs'] ]

In [12]:
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)    #Apply one-hot-encoding on our dataset
df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array
df

,Aneth,Crème glacée,Haricots rouges,Lait,Licorne,Maïs,Noix de muscade,Oignon,Pomme,Yaourt,Œufs
0,False,False,True,True,False,False,True,True,False,True,True
1,True,False,True,False,False,False,True,True,False,True,True
2,False,False,True,True,False,False,False,False,True,False,True
3,False,False,True,True,True,True,False,False,False,True,False
4,False,True,True,False,False,True,False,True,False,False,True

In [13]:
from mlxtend.frequent_patterns import apriori
apriori(df, min_support=0.6)

    support    itemsets
0       1.0         (2)
1       0.6         (3)
2       0.6         (7)
3       0.6         (9)
4       0.8        (10)
5       0.6      (2, 3)
6       0.6      (2, 7)
7       0.6      (9, 2)
8       0.8     (2, 10)
9       0.6     (10, 7)
10      0.6  (2, 10, 7)

In [14]:
frequent_itemsets=apriori(df, min_support=0.6, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

    support                         itemsets
0       1.0                (Haricots rouges)
1       0.6                           (Lait)
2       0.6                         (Oignon)
3       0.6                         (Yaourt)
4       0.8                           (Œufs)
5       0.6          (Haricots rouges, Lait)
6       0.6        (Oignon, Haricots rouges)
7       0.6        (Haricots rouges, Yaourt)
8       0.8          (Œufs, Haricots rouges)
9       0.6                   (Œufs, Oignon)
10      0.6  (Œufs, Oignon, Haricots rouges)

In [15]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7) # associate items

c:\Users\Liman\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Lait),(Haricots rouges),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
1,(Oignon),(Haricots rouges),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
2,(Yaourt),(Haricots rouges),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
3,(Œufs),(Haricots rouges),0.8,1.0,0.8,1.00,1.00,1.0,0.00,inf,0.0,0.80,0.000,0.900
4,(Haricots rouges),(Œufs),1.0,0.8,0.8,0.80,1.00,1.0,0.00,1.0,0.0,0.80,0.000,0.900
5,(Œufs),(Oignon),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
6,(Oignon),(Œufs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
7,"(Œufs, Oignon)",(Haricots rouges),0.6,1.0,0.6,1.00,1.00,1.0,0.00,inf,0.0,0.60,0.000,0.800
8,"(Œufs, Haricots rouges)",(Oignon),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
9,"(Oignon, Haricots rouges)",(Œufs),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875
10,(Œufs),"(Oignon, Haricots rouges)",0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
11,(Oignon),"(Œufs, Haricots rouges)",0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875

In [16]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="lift",min_threshold=1.25)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Oignon),(Œufs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
1,"(Oignon, Haricots rouges)",(Œufs),0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875
2,(Oignon),"(Œufs, Haricots rouges)",0.6,0.8,0.6,1.0,1.25,1.0,0.12,inf,0.5,0.75,1.0,0.875

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

# Dataset one-hot
data = [
    [1,1,0,0],  # pain lait
    [1,0,1,1],  # pain couches biere
    [0,1,1,1],  # lait couches biere
    [1,1,1,1],  # pain lait couches biere
    [1,1,1,0]   # pain lait couches
]

df = pd.DataFrame(data, columns=['pain','lait','couches','biere'])
df
freq = apriori(df, min_support=0.4, use_colnames=True)
rules = association_rules(freq, metric="confidence", min_threshold=0.6)

print(rules[['antecedents','consequents','support','confidence']])

   pain  lait  couches  biere
0     1     1        0      0
1     1     0        1      1
2     0     1        1      1
3     1     1        1      1
4     1     1        1      0